name: Java CI for Gradle
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up GraalVM 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'
      - name: Build with Gradle
        run: ./gradlew nativeCompile
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Native Image
          path: build/native/nativeCompile/*
